### ISSUE TITLE
【需求】是否可以增加对WEB的支持

### ISSUE THREAD

**Issue by qcdys** [Sky24n/flustars#34]
现在打包WEB的越来越多  大佬能否支持一下

**Comment by Sky24n** [comment]
这边只是对三方库封装，前提是他们支持web才行。
你可以使用单独库，这两个是支持web的。
```yaml
dependencies:
  # Dart common utils library. https://github.com/Sky24n/common_utils
  common_utils: ^1.2.1
  # https://github.com/Sky24n/sp_util
  sp_util: '>=1.0.0 <3.0.0'
```
